EXAMPLES = {
    "Macau": {
        "address": "Praça Ferreira do Amaral, Macau",
        "custom_title": "",
        "radius": 1100,
        "style": "Peach",
        "shape": "circle",
        "image": "macao.png",
        "name_on": False,
        "font_size": 16,
        "font_color": "#2F3737",
        "text_x": -37,
        "text_y": 26,
        "text_rotation": -45,
        "bg_shape": "rectangle",  # background
        "bg_buffer": 2,
        "bg_color": "#F2F4CB",
    },
    "Barcelona": {
        "address": "Plaça Tetuan, 08010 Barcelona, Spain",
        "custom_title": "Barcelona, Spain",
        "radius": 640,
        "style": "Auburn",
        "shape": "rectangle",
        "image": "barcelona.png",
        "name_on": True,
        "font_size": 30,
        "font_color": "#2F3737",
        "text_x": -52,
        "text_y": 20,
        "text_rotation": -90,
        "bg_shape": "rectangle",
        "bg_buffer": 2,
        "bg_color": "#F2F4CB",
    },
    "Heerhugowaard": {
        "address": "Stad van de Zon, Heerhugowaard, Netherlands",
        "custom_title": "",
        "radius": 660,
        "style": "Auburn",
        "shape": "rectangle",
        "image": "heerhugowaard.png",
        "name_on": False,
        "font_size": 24,
        "font_color": "#2F3737",
        "text_x": 0,
        "text_y": -2,
        "text_rotation": 0,
        "bg_shape": "rectangle",
        "bg_buffer": 2,
        "bg_color": "#F2F4CB",
    },
    "Edinburgh": {
        "address": "Princes St, Edinburgh, UK",
        "custom_title": "",
        "radius": 850,
        "style": "Peach",
        "shape": "circle",
        "image": "edinburgh.png",
        "name_on": False,
        "font_size": 16,
        "font_color": "#2F3737",
        "text_x": -37,
        "text_y": 26,
        "text_rotation": -45,
        "bg_shape": "rectangle",  # background
        "bg_buffer": 2,
        "bg_color": "#F2F4CB",
    },
    "Erbil": "erbil.png",
}
