EXAMPLES = {
    "Macau": {
        "address": "Praça Ferreira do Amaral, Macau",
        "radius": 1500,
        "style": "peach",
        "shape": "circle",
        "image": "macao.png",
        "name_on": False,
        "font_size": 24,
        "font_color": "#2F3737",
    },
    "Heerhugowaard": {
        "address": "Keerkring 49, 1705 Heerhugowaard, Netherlands",
        "radius": 550,
        "style": "auburn",
        "shape": "rectangle",
        "image": "heerhugowaard.png",
        "name_on": False,
        "font_size": 24,
        "font_color": "#2F3737",
    },
    "Barcelona": "barcelona.png",
    "Erbil": "erbil.png",
    "Cidadebaixa": "bomfim-farroupilha-cidadebaixa.png",
}
